# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingUserProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MasterAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Material')])),
            ],
        ),
        migrations.CreateModel(
            name='MasterProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MasterWorkable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Gentlemen'), (2, 'Women')], null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterAttribute')),
            ],
        ),
        migrations.AddField(
            model_name='masterservice',
            name='workable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterWorkable'),
        ),
        migrations.AddField(
            model_name='masterprocess',
            name='service',
            field=models.ManyToManyField(to='service_and_process.MasterService'),
        ),
        migrations.AddField(
            model_name='masterprocess',
            name='user',
            field=models.ManyToManyField(through='service_and_process.MappingUserProcess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mappinguserprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterProcess'),
        ),
        migrations.AddField(
            model_name='mappinguserprocess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
