# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MasterWorkable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Gentlemen'), (2, 'Women')])),
            ],
        ),
        migrations.AddField(
            model_name='masterservice',
            name='workable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.MasterWorkable'),
        ),
    ]
