# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingProductServicesProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MasterAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Material')])),
            ],
        ),
        migrations.CreateModel(
            name='MasterProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.MasterSection')),
            ],
        ),
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('shelf_life_in_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('batch_size', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(1, 'Piece'), (2, 'Kg')])),
            ],
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MasterWorkable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Gentlemen'), (2, 'Women')], null=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterAttribute')),
            ],
        ),
        migrations.AddField(
            model_name='masterservice',
            name='workable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterWorkable'),
        ),
        migrations.AlterUniqueTogether(
            name='masterattribute',
            unique_together=set([('label', 'type')]),
        ),
        migrations.AddField(
            model_name='mappingproductservicesprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterProcess'),
        ),
        migrations.AddField(
            model_name='mappingproductservicesprocess',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterProduct'),
        ),
        migrations.AddField(
            model_name='mappingproductservicesprocess',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterService'),
        ),
    ]
