# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_and_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterworkable',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterAttribute'),
        ),
        migrations.AlterUniqueTogether(
            name='masterattribute',
            unique_together=set([('label', 'type')]),
        ),
    ]
