# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.InternalUser')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(verbose_name=((1, 'Laundry'), (2, 'Kitchen')))),
            ],
        ),
        migrations.AddField(
            model_name='internaluser',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.MasterSection'),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
