# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
