# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20161113_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersection',
            name='label',
            field=models.TextField(),
        ),
    ]
