# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20161113_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaluser',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.InternalUser'),
        ),
    ]
