# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20161113_0554'),
        ('people', '0004_auto_20161113_0530'),
    ]

    operations = [
    ]
