# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaluser',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.InternalUser'),
        ),
        migrations.AlterField(
            model_name='mastersection',
            name='label',
            field=models.IntegerField(choices=[(1, 'Laundry'), (2, 'Kitchen')]),
        ),
    ]
