# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20161113_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersection',
            name='label',
            field=models.IntegerField(unique=True),
        ),
    ]
