# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('service_and_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MappingProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterProduct')),
            ],
        ),
        migrations.CreateModel(
            name='MappingTrainerTraineeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MasterRawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('unit', models.IntegerField(verbose_name=((1, 'piece'), (2, 'kg')))),
            ],
        ),
        migrations.CreateModel(
            name='MasterTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name=((1, 'In Use'), (2, 'Free')))),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('expected_timestamp', models.DateTimeField()),
                ('completed_timestamp', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('expected_quantity', models.IntegerField()),
                ('output_quantity', models.IntegerField(null=True)),
                ('type', models.IntegerField(choices=[(1, 'Training'), (2, 'Actual')])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_system.Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.TextField()),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.IntegerField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_system.MasterRawMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_timestamp', models.DateTimeField()),
                ('completed_timestamp', models.DateTimeField()),
                ('is_success', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_system.Item')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterProcess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.InternalUser')),
            ],
        ),
        migrations.AddField(
            model_name='mappingtrainertraineetask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_system.Task'),
        ),
        migrations.AddField(
            model_name='mappingtrainertraineetask',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to='people.InternalUser'),
        ),
        migrations.AddField(
            model_name='mappingtrainertraineetask',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='people.InternalUser'),
        ),
        migrations.AddField(
            model_name='mappingproductmaterial',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_system.MasterRawMaterial'),
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_system.Order'),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterProduct'),
        ),
        migrations.AddField(
            model_name='item',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterService'),
        ),
        migrations.AddField(
            model_name='item',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_system.MasterTag'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_system.MasterRawMaterial'),
        ),
    ]
