# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='type',
            new_name='production_type',
        ),
        migrations.AlterField(
            model_name='masterrawmaterial',
            name='unit',
            field=models.IntegerField(choices=[(1, 'piece'), (2, 'kg')]),
        ),
        migrations.AlterField(
            model_name='mastertag',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Use'), (2, 'Free')]),
        ),
    ]
