# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_and_process', '0002_auto_20161113_0502'),
        ('production_system', '0002_auto_20161113_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('update_timestamp', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterProduct')),
            ],
        ),
    ]
